- src/Pages/ContactPage/ContactPage.jsx
- src/Pages/ContactPage/ContactPage.scss
> TBW 48 - Add embeded map

- src/Components/CustomServicesNav/CustomServicesNav.jsx
- src/Components/CustomServicesNav/CustomServicesNav.scss
- src/Components/Service/Service.jsx
- src/Pages/ServicesPage/ServicesPage.jsx
Maybe we should add a scroll to top button on all of our pages?
resolves #33
> TBW 33 - Add scrolling on button click

- backend/package.json
- backend/server.js
- frontend/package.json
- frontend/src/Components/ContactForm/ContactForm.jsx
- frontend/src/Components/ContactForm/ContactForm.scss
- frontend/src/Components/ContactForm/index.js
- frontend/src/Components/index.js
- frontend/src/Pages/ContactPage/ContactPage.jsx
- frontend/src/Pages/ContactPage/ContactPage.scss
- frontend/src/Utils/EmailSending.jsx
- frontend/src/Utils/index.js
Half of the work for this ticket is done with the implementation of email sending on the contact page and the use of frontend validation.
To-do:
Email sending on careers page
Frontend validation on careers page
Frontend error rendering
> TBW 8 - Add email sending to contact page

- frontend/src/Components/CustomToolbar/CustomToolbar.jsx
- frontend/src/Components/CustomToolbar/CustomToolbar.scss
- frontend/src/Styles/App.scss
> Add Nav underlining

- frontend/src/Components/CustomToolbar/CustomToolbar.jsx
- frontend/src/Pages/AboutPage/AboutPage.jsx
- frontend/src/Pages/CareersPage/CareersPage.jsx
- frontend/src/Pages/ContactPage/ContactPage.jsx
- frontend/src/Pages/ProjectsPage/ProjectsPage.jsx
- frontend/src/Pages/ServicesPage/ServicesPage.jsx
> Remove transition when not on landing page

- frontend/src/Components/CustomToolbar/CustomToolbar.jsx
- frontend/src/Components/CustomToolbar/CustomToolbar.scss
- frontend/src/Components/LanguageMenu/LanguageMenu.jsx
- frontend/src/Components/LanguageMenu/LanguageMenu.scss
- frontend/src/Components/LanguageMenu/index.js
- frontend/src/Components/index.js
- frontend/src/Pages/AboutPage/AboutPage.jsx
- frontend/src/Utils/functions.jsx
Changelog:
- Fixed icons being too large
- Fixed site crash on selecting outside of language menu
- Moved language menu to separate component
- Fixed some key issues
resolves #74
> TBW-74 fixed issues in language menu and small key fixes

- frontend/public/index.html
> TBW-65 Update meta description

- frontend/package.json
- frontend/src/Components/CareersForm/CareersForm.jsx
- frontend/src/Components/CareersForm/CareersForm.scss
- frontend/src/Components/ContactForm/ContactForm.jsx
- frontend/src/Components/ContactForm/ContactForm.scss
- frontend/src/Components/CustomServicesNav/CustomServicesNav.scss
- frontend/src/Components/CustomToolbar/CustomToolbar.jsx
- frontend/src/Components/CustomToolbar/CustomToolbar.scss
- frontend/src/Components/PageHeader/PageHeader.scss
- frontend/src/Pages/LandingPage/LandingPage.scss
- frontend/src/Styles/Variables.scss
- frontend/src/index.jsx
Lots of changes being made here, should probably update master
> TBW-24 General responsive updates

- frontend/src/Components/CustomServicesNav/CustomServicesNav.scss
- frontend/src/Components/Service/Service.scss
- frontend/src/Pages/ServicesPage/ServicesPage.jsx
- frontend/src/Pages/ServicesPage/ServicesPage.scss
- frontend/src/Styles/Colours.scss
Changelog:
- Fixed mobile services navbar to stick on scrolling
> TBW-24 Bug fixes and Sticky Services Bar

- frontend/package.json
- frontend/src/Components/CustomServicesNav/CustomServicesNav.jsx
- frontend/src/Components/CustomServicesNav/CustomServicesNav.scss
- frontend/src/Components/Service/Service.jsx
- frontend/src/Components/Service/Service.scss
- frontend/src/Pages/ServicesPage/ServicesPage.jsx
- frontend/src/Styles/Colours.scss
> TBW 79 - Add scrollspy

- .ebextensions/secrets.config
- Dockerrun.aws.json
- backend/server.js
- docker-compose.yml
- reverseproxy/Dockerfile
- reverseproxy/dummy.sh
> TBW-59 Add secret deployment for backend

- frontend/src/Components/CareersForm/CareersForm.jsx
- frontend/src/Components/CareersForm/CareersForm.scss
> TBW-8 Add file clearing on email submission

- frontend/src/Components/CareersForm/CareersForm.scss
- frontend/src/Components/CustomServicesNav/CustomServicesNav.jsx
- frontend/src/Components/CustomServicesNav/CustomServicesNav.scss
- frontend/src/Components/Service/Service.jsx
- frontend/src/Components/Service/Service.scss
- frontend/src/Pages/AboutPage/AboutPage.jsx
- frontend/src/Pages/AboutPage/AboutPage.scss
- frontend/src/Pages/LandingPage/LandingPage.jsx
- frontend/src/Pages/LandingPage/LandingPage.scss
- frontend/src/Styles/Variables.scss
- frontend/src/Values/locales/en/translation.json
> TBW-24 Update CustomServicesNav styles

- frontend/package.json
- frontend/src/Components/ContactForm/ContactForm.scss
- frontend/src/Components/CustomDivider/CustomDivider.jsx
- frontend/src/Components/CustomDivider/CustomDivider.scss
- frontend/src/Pages/ContactPage/ContactPage.jsx
- frontend/src/Pages/ContactPage/ContactPage.scss
- frontend/src/Pages/LandingPage/LandingPage.scss
- frontend/src/Styles/Colours.scss
- frontend/src/Styles/Variables.scss
Changelog:
- Added `@material-ui/lab` to make use of skeleton on the contact page
- Updated `@material-ui/core` to 4.9.8 to support `@material-ui/lab`
- Fixed landing page so every second section is dark mode
- Changed landing page font colours to be lower contrast for visibility
- Added lorem ipsum text to divider.
> TBW-89 Fixed landing and added skeleton to landing

- .ebextensions/secrets.config
- Dockerrun.aws.json
- docker-compose.yml
- reverseproxy/nginx.conf
Changelog:
- Added password file to secure the nginx reverseproxy to hide the website
> TBW-91 Added password to the pages to hide from the web

- frontend/src/Components/CustomServicesNav/CustomServicesNav.scss
- frontend/src/Pages/ServicesPage/ServicesPage.scss
Changelog:
- Converted mobile services nav to scroll instead of overflow.
> TBW-98 Changed mobile sticky nav on services to scroll

- Makefile
- backend/.eslintrc
- backend/package.json
- frontend/package.json
Changelog:
- Removed React linting from backend through changing `airbnb` to `airbnb-base`
- Fixed linting and testing configs in makefile to speed up processing and ease developer use
> TBW-104 added makefile support for linting and testing

- frontend/src/Components/CustomServicesNav/CustomServicesNav.scss
Updated the styles for `CustomServicesNav` to resemble the top bar more
resolves #103
> Update CustomServicesNav styles

- frontend/src/Components/CareersForm/CareersForm.jsx
- frontend/src/Components/CareersForm/CareersForm.scss
- frontend/src/Values/locales/en/translation.json
- frontend/src/Values/locales/fr/translation.json
Added the space for file restrictions, need content for this obviously.
resolves #98
> Add text for file restrictions

- backend/api/send-email.js
- backend/routes/index.js
- frontend/src/Components/CareersForm/CareersForm.jsx
- frontend/src/Components/ContactForm/ContactForm.jsx
- frontend/src/Utils/Requests.jsx
Client token was expired after inactivity in 6 months... this could possibly happen again, but we'll cross that bridge when we get there.
Also, update backend validation.
Also, show error toasts more freely in the frontend
> 117 - Fix form submissions

- frontend/src/Pages/AboutPage/AboutPage.jsx
- frontend/src/Pages/AboutPage/AboutPage.scss
- frontend/src/Styles/Variables.scss
- frontend/src/Values/locales/en/translation.json
Add padding to `AboutPage` sections
Update body `font-size`
Add image captions to `AboutPage`
> Update AboutPage content

- frontend/src/Components/CustomServicesNav/CustomServicesNav.jsx
- frontend/src/Components/CustomServicesNav/CustomServicesNav.scss
- frontend/src/Components/ServiceCard/ServiceCard.jsx
- frontend/src/Components/ServiceCard/ServiceCard.scss
- frontend/src/Pages/AboutPage/AboutPage.jsx
- frontend/src/Pages/AboutPage/AboutPage.scss
- frontend/src/Pages/ServicesPage/ServicesPage.jsx
- frontend/src/Styles/Variables.scss
- frontend/src/Values/locales/en/translation.json
Add image captions to services
Add ellipses overflow on services options
Update scroll to on service options based on screen size
> Update Service content

- frontend/src/Components/CustomFooter/CustomFooter.jsx
- frontend/src/Pages/ContactPage/ContactPage.jsx
- frontend/src/Values/locales/en/translation.json
- frontend/src/Values/locales/fr/translation.json
**Proposed Changes**
- Remove email from footer and contact page
- Remove redundancy in the street address
resolves #118
> 118 - Remove email from footer and contact page
